<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderRecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends EntityRepository
{
    public function findFulfilledOrders($month = null, $year = null)
    {
        $emConfig = $this->getEntityManager()->getConfiguration();
        $emConfig->addCustomDatetimeFunction('YEAR', \DoctrineExtensions\Query\Mysql\Year::class);
        $emConfig->addCustomDatetimeFunction('MONTH', \DoctrineExtensions\Query\Mysql\Month::class);

        $orders = $this->getEntityManager()->createQueryBuilder()
            ->select('o')
            ->from(\App\Entity\Order::class, 'o')
            ->where('o.fulfilled = 1')
            ->orderBy('o.created', 'DESC');

        if (empty($month) && empty($year)) {
            $orders
                ->andWhere('o.created > ?1')
                ->setParameter(1, strtotime('-3 months'));
            ;
        }

        if (!empty($month)) {
            $orders
                ->andWhere('MONTH(o.created) = ?2')
                ->setParameter(2, $month);
        }

        if (!empty($year)) {
            $orders
                ->andWhere('YEAR(o.created) = ?3')
                ->setParameter(3, $year);
        }

        return $orders->getQuery()->getResult();
    }
}
