<?php
namespace App\Form\Type;

use Symfony\Component\Form\FormBuilderInterface;

class RegisterType extends CustomerType
{
    use PasswordType {
        buildForm as _buildForm;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $this->_buildForm($builder, $options);
    }
}
